# THIS IS NOT A PRODUCTION SETUP - LAB USE ONLY!
services:
    oracle:
        # the current image container-registry.oracle.com/database/free:23.8.0.0
        # does not work on Debian/Ubuntu/Mint
        image: docker.io/gvenzl/oracle-free:23.8
        ports:
            - 1521:1521
        environment:
            - ORACLE_PASSWORD=changeOnInstall
            - APP_USER=demouser
            - APP_USER_PASSWORD=demouser
        volumes:
            - oradata-vol:/opt/oracle/oradata
            - ./initialisation:/container-entrypoint-initdb.d:Z
        networks:
            - backend
        healthcheck:
            test: ["CMD", "healthcheck.sh"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 5s
            start_interval: 5s

    ords:
        depends_on:
            oracle:
                condition: service_healthy
        image: container-registry.oracle.com/database/ords:25.2.0
        environment:
            - CONN_STRING=oracle/freepdb1
            - ORACLE_PWD=changeOnInstall
        networks:
            - backend
        ports:
            - 8080:8080
            - 8443:8443
            - 27017:27017
        volumes:
            - ords-config-vol:/etc/ords/config
            - ./apex:/opt/oracle/apex:Z

volumes:
    oradata-vol:
    ords-config-vol:

networks:
    backend: