# THIS IS NOT A PRODUCTION SETUP - LAB USE ONLY!
services:
  oracle:
    image: container-registry.oracle.com/database/free:23.8.0.0
    ports:
      - 1521:1521
    environment:
      - ORACLE_PASSWORD=changeOnInstall
      - ORACLE_PDB=freepdb1
      - DBHOST=db
    volumes:
      - oradata-vol:/opt/oracle/oradata
      - ./initialisation:/opt/oracle/scripts/startup
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "/opt/oracle/checkDBStatus.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  oradata-vol:

networks:
  backend:
